### ISSUE TITLE
If MusterCull severely nerfs herd size, should up drop % for Eggs.

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/ArthropodEgg#2]
Title.

Easy change, but wanted to open an issue to facilitate discussion in case this isn't the no-brainer I think it is.

**Comment by ttk2** [comment]
drop multipliers should take care of it, but I guess exactly where we do
the buff is a matter of programming semantics and organization enough for
us to talk about.

**Comment by ProgrammerDan** [comment]
Does drop multiplier affect spawn egg drops, though? I'd been assuming not, but haven't traced the code to verify.

**Comment by ttk2** [comment]
drop multiplier should affect all drops except explicitly the pick up drops
from spawner mobs.
